CREATE TABLE  "ASSISTS" 
   (	"AS_RID" CHAR(4) NOT NULL ENABLE, 
	"AS_DID" CHAR(4) NOT NULL ENABLE, 
	 PRIMARY KEY ("AS_RID", "AS_DID") ENABLE
   ) ;ALTER TABLE  "ASSISTS" ADD FOREIGN KEY ("AS_RID")
	  REFERENCES  "RECEPTIONIST" ("R_ID") ENABLE;ALTER TABLE  "ASSISTS" ADD FOREIGN KEY ("AS_DID")
	  REFERENCES  "DONOR" ("D_ID") ENABLE;
INSERT INTO ASSISTS VALUES ('E011', 'D001');
INSERT INTO ASSISTS VALUES ('E012', 'D002');
INSERT INTO ASSISTS VALUES ('E013', 'D003');
INSERT INTO ASSISTS VALUES ('E014', 'D004');
INSERT INTO ASSISTS VALUES ('E015', 'D005');
