CREATE TABLE  "EXAMINATION" 
   (	"EXAMIN_LID" CHAR(4) NOT NULL ENABLE, 
	"EXAMIN_DID" CHAR(4) NOT NULL ENABLE, 
	"EXAMIN_BSID" CHAR(4) NOT NULL ENABLE, 
	"DATE_EXAMIN" DATE, 
	 PRIMARY KEY ("EXAMIN_LID", "EXAMIN_DID", "EXAMIN_BSID") ENABLE
   ) ;ALTER TABLE  "EXAMINATION" ADD FOREIGN KEY ("EXAMIN_LID")
	  REFERENCES  "LAB_SPECIALIST" ("L_ID") ENABLE;ALTER TABLE  "EXAMINATION" ADD FOREIGN KEY ("EXAMIN_DID", "EXAMIN_BSID")
	  REFERENCES  "BLOODSTOCK" ("BS_DID", "BLOODSTOCK_ID") ENABLE;
INSERT INTO EXAMINATION VALUES ('E006', 'D001', 'BS01', '05-20-2023');
INSERT INTO EXAMINATION VALUES ('E007', 'D002', 'BS02', '06-24-2023');
INSERT INTO EXAMINATION VALUES ('E008', 'D003', 'BS03', '07-24-2023');
INSERT INTO EXAMINATION VALUES ('E009', 'D004', 'BS04', '08-24-2023');
INSERT INTO EXAMINATION VALUES ('E010', 'D005', 'BS05', '09-24-2023');
