CREATE TABLE  "LAB_SPECIALIST" 
   (	"L_ID" CHAR(4) NOT NULL ENABLE, 
	"LABORATORY_CERTIFICATE" VARCHAR2(30) NOT NULL ENABLE, 
	 PRIMARY KEY ("L_ID") ENABLE
   ) ;ALTER TABLE  "LAB_SPECIALIST" ADD FOREIGN KEY ("L_ID")
	  REFERENCES  "EMPLOYEE" ("EMP_ID") ON DELETE CASCADE ENABLE;
      INSERT INTO LAB_SPECIALIST VALUES ('E006', 'L001');
INSERT INTO LAB_SPECIALIST VALUES ('E007', 'L002');
INSERT INTO LAB_SPECIALIST VALUES ('E008', 'L003');
INSERT INTO LAB_SPECIALIST VALUES ('E009', 'L004');
INSERT INTO LAB_SPECIALIST VALUES ('E010', 'L005');
