
CREATE TABLE "RECEPTIONIST" 
(
    "R_ID" CHAR(4) NOT NULL ENABLE, 
    "TYPING_SPEED" NUMBER(*,0) NOT NULL ENABLE, 
    PRIMARY KEY ("R_ID") ENABLE
);

ALTER TABLE "RECEPTIONIST" ADD FOREIGN KEY ("R_ID")
REFERENCES "EMPLOYEE" ("EMP_ID") ON DELETE CASCADE ENABLE;
INSERT INTO RECEPTIONIST VALUES ('E011', '20');
INSERT INTO RECEPTIONIST VALUES ('E012', '35');
INSERT INTO RECEPTIONIST VALUES ('E013', '45');
INSERT INTO RECEPTIONIST VALUES ('E014', '23');
INSERT INTO RECEPTIONIST VALUES ('E015', '15'); 
